services:
  github-archive:
    image: ghcr.io/sweenyxsky-oss/github-archive:latest
    restart: unless-stopped
    environment:
      TZ: Asia/Riyadh
      GITHUB_TOKEN: ""
      CHECK_INTERVAL_MINUTES: "360"
      INCLUDE_PRERELEASES: "false"
      MAX_DOWNLOAD_RETRIES: "4"
      DOWNLOAD_WORKERS: "2"
      WEBHOOK_SECRET: ""
      ADMIN_TOKEN: ""
    ports:
      - "8088:8080"
    volumes:
      - /mnt/dataPool/GitHubArchive:/data
